# Generated by Django 4.1.7 on 2023-03-31 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('date_range', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('pay_cycle', models.IntegerField()),
                ('rate', models.FloatField()),
                ('earnings_allowance', models.FloatField()),
                ('deductions_tax', models.FloatField()),
                ('deductions_health', models.FloatField()),
                ('pag_ibig', models.FloatField()),
                ('sss', models.FloatField()),
                ('overtime', models.FloatField()),
                ('total_pay', models.FloatField()),
                ('id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee')),
            ],
        ),
    ]
