# Generated by Django 4.1.7 on 2023-04-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_alter_employee_rate_payslip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
