# Generated by Django 4.1.7 on 2023-04-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0003_alter_employee_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='pag_ibig',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='sss',
            field=models.FloatField(default=0.045),
        ),
    ]
